name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: PowerOverInternet

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Initialize test reporting
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}
    
    - name: Restore
      run: dotnet restore --locked-mode --verbosity normal

    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal

    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --settings Tests/Tests.runsettings --logger "trx;LogFileName=TestResults.xml"
        mv Tests/TestResults/*/coverage.info Tests/TestResults

    - name: Publish
      run: |
        dotnet publish ${{ env.ProjectName }} --no-build --configuration Release -p:PublishSingleFile=false --no-self-contained --verbosity normal
        Remove-Item .\${{ env.ProjectName }}\bin\Release\net8.0\publish\appsettings.Development.json
        Remove-Item .\${{ env.ProjectName }}\bin\Release\net8.0\publish\${{ env.ProjectName }}.pdb
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}
        path: ${{ env.ProjectName }}\bin\Release\net8.0\publish\*

    - name: Upload test report
      run: testspace Tests/TestResults/TestResults.xml

    - name: Upload coverage
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: Tests/TestResults/coverage.info
        format: lcov